# Generated by Django 5.0.7 on 2024-08-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_image', models.ImageField(upload_to='images/')),
                ('dr_name', models.CharField(max_length=50)),
                ('dr_prof', models.CharField(max_length=100)),
                ('summary', models.CharField(max_length=500)),
            ],
        ),
    ]
